# Generated by Django 2.2.10 on 2020-03-02 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercury', '0007_events_field_general_data_sensor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='General_data',
            new_name='GeneralData',
        ),
    ]
